FROM fedora:39

RUN dnf update -y
RUN dnf install gcc make -y

COPY src ./src/
COPY include ./include/
COPY tests ./tests/
COPY Makefile .
RUN make release -j $(nproc)

RUN cc -o basic tests/basic.c -nostdlib -Ltarget/release/ -Iinclude -lexalt
CMD ["./basic"]
